export const ErrorCode = {
  AVAILABLE_COPIES_EXCEEDS_TOTAL: 'AVAILABLE_COPIES_EXCEEDS_TOTAL',
  BOOK_HAS_AVAILABLE_COPIES: 'BOOK_HAS_AVAILABLE_COPIES',
  DUPLICATE_LOAN: 'DUPLICATE_LOAN',
  LOAN_LIMIT_REACHED: 'LOAN_LIMIT_REACHED',
  NO_COPIES_AVAILABLE: 'NO_COPIES_AVAILABLE',
  USER_NOT_ACTIVE: 'USER_NOT_ACTIVE',
} as const

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode]
